name: scramjet
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dotenv: ^4.0.1
  json_annotation: ^4.7.0
  meta: ^1.8.0
  mqtt5_client: ^3.3.2
